version: '3.1'

networks:
  network-zabbix:
    driver: bridge

services:
  db:
    image: mysql:5.7
    networks:
      - network-zabbix
    ports:
      - '3306:3306'
    volumes:
      - './volume/db:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=carryontech
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=emer888

  server:
    image: zabbix/zabbix-server-mysql:ubuntu-5.0.1
    networks:
      - network-zabbix
    depends_on:
      - db
    ports:
      - '10051:10051'
    volumes:
      - './volume/app/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=emer888

  app:
    image: zabbix/zabbix-web-apache-mysql:ubuntu-5.0.1
    networks:
      - network-zabbix
    depends_on:
      - db
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=emer888
      - PHP_TZ=America/Sao_Paulo

  grafana:
    image: grafana/grafana
    networks:
      - network-zabbix
    depends_on:
      - db
      - app
    ports:
      - '3000:3000'
    environment: 
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app

  agent:
    image: zabbix/zabbix-agent2:alpine-5.0.1
    networks:
      - network-zabbix
    depends_on:
      - app
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=ZabbixServer
      - ZBX_SERVER_HOST=server
