version: '3.1'

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.4.0/24

services:
  db:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - './volume/db:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=carryontech
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=emer888
    networks:
      network:
        ipv4_address: 10.0.4.3

  server:
    image: zabbix/zabbix-server-mysql:ubuntu-6.2.9
    depends_on:
      - db
    ports:
      - '10051:10051'
    volumes:
      - './volume/app/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=emer888
    networks:
      network:
        ipv4_address: 10.0.4.4

  app:
    image: zabbix/zabbix-web-apache-mysql:ubuntu-6.2.9
    depends_on:
      - db
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=emer888
      - PHP_TZ=America/Sao_Paulo
    networks:
      network:
        ipv4_address: 10.0.4.2

  grafana:
    image: grafana/grafana
    depends_on:
      - db
      - app
    ports:
      - '3000:3000'
    environment: 
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    networks:
      network:
        ipv4_address: 10.0.4.6

  agent:
    image: zabbix/zabbix-agent2:alpine-6.2.9
    depends_on:
      - app
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=ZabbixServer
      - ZBX_SERVER_HOST=server
    networks:
      network:
        ipv4_address: 10.0.4.5
