version: '3.9'

services:
  db:
    image: postgres:15.1-bullseye
    hostname: pgsql
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - /srv/volumes/zabbix/db_pgsql/_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      zbx:
        ipv4_address: 172.30.0.2

  server:
    hostname: zabbix-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    pull_policy: always
    environment:
      - DB_SERVER_HOST=db
      - DB_SERVER_PORT=${POSTGRES_PORT}
      - DB_SERVER_DBNAME=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ZBX_LISTENPORT=10051
      - PHP_TZ=America/Sao_Paulo
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /srv/volumes/zabbix/server-module/_data:/var/lib/zabbix/modules
      - /srv/volumes/zabbix/server/externalscripts/_data:/usr/lib/zabbix/externalscripts:ro
      - /srv/volumes/zabbix/server/alertscripts/_data:/usr/lib/zabbix/alertscripts:ro
    networks:
      zbx:
        ipv4_address: 172.30.0.3   # IP fixo do Zabbix Server

  frontend:
    hostname: zabbix_frontend
    image: zabbix/zabbix-web-apache-pgsql:ubuntu-trunk
    restart: always
    pull_policy: always
    environment:
      - DB_SERVER_HOST=db
      - DB_SERVER_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ZBX_SERVER_HOST=server
      - ZBX_SERVER_PORT=10051
      - PHP_TZ=America/Sao_Paulo
    depends_on:
      db:
        condition: service_healthy
      server:
        condition: service_started
    ports:
      - 9014:8080
      - 9015:443
    networks:
      zbx:
        ipv4_address: 172.30.0.4

networks:
  zbx:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1
