# version: '2.4'
services:
  frontend:
    # container_name: pcmonitor-frontend
    hostname: frontend 
    image: zabbix/zabbix-web-apache-pgsql:ubuntu-trunk
    restart: always
    pull_policy: always
    environment:
      # - DB_SERVER_HOST=10.200.0.10
      - DB_SERVER_HOST=pgsql
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # - ZBX_SERVER_HOST=10.200.0.7
      - ZBX_SERVER_HOST=server 
      - PHP_TZ=America/Sao_Paulo
    # networks:
    #   - default
    #     ipv4_address: 10.200.0.8
    #   nginx_network:
    #     ipv4_address: 10.0.2.4  
    ports:
      - 9014:8080
      - 9015:443
    volumes:
      - /srv/volumes/zabbix-frontend/ssl.key/_data:/etc/ssl/apache2/ssl.key
      - /srv/volumes/zabbix-frontend/ssl.crt/_data:/etc/ssl/apache2/ssl.crt
      # - ./volume/srv/volumes/zabbix-frontend/ssl.key:/etc/ssl/apache2/ssl.key
      # - ./volume/srv/volumes/zabbix-frontend/ssl.crt:/etc/ssl/apache2/ssl.crt

  server:
    # container_name: pcmonitor-server
    hostname: server 
    # image: zabbix/zabbix-server-pgsql:ol-trunk
    image: zabbix/zabbix-server-pgsql:ubuntu-trunk
    restart: always
    pull_policy: always
    environment:
      # - DB_SERVER_HOST=10.200.0.10
      - DB_SERVER_HOST=pgsql
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      # - ./volume/srv/volumes/zabbix-server-module:/var/lib/zabbix/modules
      - /srv/volumes/zabbix-server-module/_data:/var/lib/zabbix/modules
    # networks:
    #   - default
    #     ipv4_address: 10.200.0.7
    # ports:
    #   - "161:161/udp"  # Aqui você está expondo a porta 161 UDP
      # - "161:161"  # Aqui você está expondo a porta 161 UDP
      # - "50000-60000:50000-60000"



  
  pgsql:
    # container_name: pcmonitor-pgsql
    hostname: pgsql 
    image: postgres:15.1-bullseye
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - /srv/volumes/zabbix-pgsql/_data:/var/lib/postgresql/data
      # - ./volume/srv/volumes/zabbix-pgsql:/var/lib/postgresql/data
    # networks:
    #   - default
    #    ipv4_address: 10.200.0.10
    ports:
      - 5432:5432

# networks:
#   default:
#     driver: bridge


  #   ipam:
  #     config:
  #       - subnet: 10.200.0.0/24
  #         gateway: 10.200.0.1
  # nginx_network:
  #   external: true
