services:
  frontend:
    hostname: frontend 
    image: zabbix/zabbix-web-apache-pgsql:ubuntu-trunk
    restart: always
    pull_policy: always
    environment:
      - DB_SERVER_HOST=pgsql
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ZBX_SERVER_HOST=server 
      - PHP_TZ=America/Sao_Paulo
    ports:
      - 9014:8080
      - 9015:443
    volumes:
      - /srv/volumes/zabbix-frontend/ssl.key/_data:/etc/ssl/apache2/ssl.key
      - /srv/volumes/zabbix-frontend/ssl.crt/_data:/etc/ssl/apache2/ssl.crt

  server:
    hostname: server 
    image: zabbix/zabbix-server-pgsql:ubuntu-trunk
    restart: always
    pull_policy: always
    environment:
      - DB_SERVER_HOST=pgsql
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - /srv/volumes/zabbix-server-module/_data:/var/lib/zabbix/modules
  
  pgsql:
    hostname: pgsql 
    image: postgres:15.1-bullseye
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - /srv/volumes/zabbix-pgsql/_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

